//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALProjet2017AL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATIONs
    {
        public int ID { get; set; }
        public int PROMOTION { get; set; }
        public int MATIERE { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime HEURE_DEBUT { get; set; }
        public System.DateTime HEURE_FIN { get; set; }
        public int SALLE { get; set; }
        public int PROFESSEUR { get; set; }
    
        public virtual RESERVATIONs RESERVATIONs1 { get; set; }
        public virtual RESERVATIONs RESERVATIONs2 { get; set; }
    }
}
