//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALProjet2017AL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALLE
    {
        public int id_salle { get; set; }
        public string nom_salle { get; set; }
        public string adresse_salle { get; set; }
    }
}
